version: "3"
services:
  frontend:
    restart: unless-stopped
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11092505-my-assignment-repo:frontend
    build: ./frontend
    ports:
      - "80:80"
  
  # backend:
  #   restart: unless-stopped
  #   image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11092505-my-assignment-repo:backend
  #   build: ./backend
  #   ports:
  #     - "3000:3000"